name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: ghaction-cmake
      uses: lpenz/ghaction-cmake@v0.1
  
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Generate Doxygen documentation
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          working-directory: '.'
          doxyfile-path: '../docs/Doxyfile'
          
